[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "photoprot"
version = "0.1.0"
description = "Predicting protein structure class and identity from 2D rendered images"
license = {file = "LICENSE"}
authors = [
    {name = "Nichita Mitrea", email = "nichmitrea22@gmail.com"},
    {name = "Ahura Farhadi", email = "ahura.farhadi03@gmail.com"},
]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "pyarrow",
    "requests",
    "tqdm",
    "gemmi",
    "pydssp",
    "einops",
    "scikit-learn",
    "lightgbm",
]

[tool.setuptools.packages.find]
include = ["photoprot*"]
